{% set name = "f3dasm" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/f3dasm-{{ version }}.tar.gz
  sha256: 9619dc3568fa416a49a7ae135c73630fa12a54ca3011ef5b29d3b2c7fccb0895

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy <2.0.0
    - scipy
    - pandas
    - xarray
    - matplotlib-base
    - hydra-core
    - pathos >=0.3.0
    - autograd
    - salib
    - filelock

test:
  imports:
    - f3dasm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bessagroup/f3dasm
  summary: f3dasm - Framework for Data-driven Development and Analysis of Structures and Materials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mpvanderschelling
