{% set name = "f3dasm" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/f3dasm-{{ version }}.tar.gz
  sha256: 621b1871bfa590a5a321a7e5f76e8fb4897693f4765e0a05e372a466e3fe6501

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=43.0.0
    - wheel
    - pip
  run:
    - python >=3.8
    - numpy
    - scipy
    - pandas
    - xarray
    - matplotlib-base
    - hydra-core
    - pathos >=0.3.0
    - autograd
    - salib
    - filelock

test:
  imports:
    - f3dasm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bessagroup/f3dasm
  summary: f3dasm - Framework for Data-driven Development and Analysis of Structures and Materials
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mpvanderschelling
